server:
  port: 8006

spring:
  application:
    name: springcloud-payment-consul
  cloud:
    consul:
      host: 192.168.1.8  #用linux的ip地址（consul在本机就填localhost）
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        healthCheckPath: health
        prefer-ip-address: true
        heartbeat:
          enabled: true
        health-check-path: health