server:
  port: 80

spring:
  application:
    name: springcloud-order-consul

  cloud:
    consul:
      host: 192.168.1.8
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true
        health-check-path: health