server:
  port: 8002
spring:
  application:
    name: springcloud-payment
  profiles:
    active: dev

eureka:
  client:
    #客户端提供者需要向eureka注册
    register-with-eureka: true
    #客户端向注册中心抓取已有的注册服务
    fetch-registry: true
    service-url:
      #eureka交互地址,查询服务和注册服务都需要用到这个地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002  #eureka显示的名称
    prefer-ip-address: true   #是否显示IP地址

