server:
  port: 80

spring:
  application:
    name: springcloud-order-feign

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

ribbon:
  ReadTimeout: 5000
  ConnectionTimeout: 5000

logging:
  level:
    #设定监控哪个service
    com.hangyang.service.PaymentFeignService: debug
